// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtglsxsscxqpividdfsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Z2xzeHNzY3hxcGl2aWRkZnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjcwMDEsImV4cCI6MjA3MTI0MzAwMX0.n2ZfjXus-zZVFiIRVoMzFWPLF86jrsmIg0v3oYPo1AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});